module.exports = {
  reactStrictMode: true,
  images: {
    domains: ['assets.teenvogue.com','www.al3nan.com',"i.pinimg.com","static.wikia.nocookie.net","wikipedia",'s3.images-iherb.com'],
  },
}
/** 
BODY SHAVING OR WAX
ARMS – 40/80 AED
UNDERARMS – 30/60 AED
CHEST – 50/100 AED
BACK – 50/100 AED
FULL LEGS – 60/120 AED
FULL BODY – 175/300 AED
NOSE – 00/10
EARS – 00/10
 */
/**
FACE & BODY CARE
MANICURE – 30 AED
PEDICURE – 40 AED
FOOT SPA – 50 AED
MOROCCAN BATH – 150 AED
HEAD OIL MASSAGE – 30 AED
EXPRESS FACIAL – 40 AED
EXECUTIVE FACIAL – 75 AED
QUALITY FIX FACIAL – 170 AED
CASMARA AGE DEFENCE – 375 AED
CASMARA WHITENING FACIAL – 375 AED
CASMARA SKIN SENSATION – 375 AED
CASMARA SHINE STOP – 375 AED
CASMARA WITH SKIN PEELING – 99 AED
CASMARA MASK – 70 AED
NOSE STRIP – 10 AED */
/**
 * 
BEARD & MUSTACHE
TRIM & SHAVE (Beard) – 25 AED
SHAVE & COLOR – 60 AED
THREADING – 10 AED
 */
/**
 * 
 * 
HAIR CARE TREATMENT
(Depends on length)

HAIR DYE – 80* AED
HIGHLIGHTS & LOWLIGHTS – 100 AED
PRE – WASHED (HAIR BLEACH) – 100 AED     
HAIR RELAXING – 100 AED
COLOR SHINE – 100 AED
HAIR SPA OR HAIR MASK – 80 AED
ANTI DANDRUFF OR DRY SCALP – 100 AED
ANTI HAIR FALL OR HAIR LOSS – 100 AED
HAIR PERMING – 250 AED
REBONDING – 300 AED
KERATIN – 300 AED
BOTOX – 250 AE
 */
/**
 

 */